### ISSUE TITLE
BlockLength of Control Option SuboptionStop is wrong

### ISSUE THREAD

**Issue by chgieseler** [fbarresi/ProfinetTools#1]
According to PN-AL-protocol_2722_V23Ed2MU4_Mar17 table 73 the Coding of DCPBlockLenth in conjunction with Suboption Stop shall be 0x2. All other values are reserved. In the current implementation the value is 2 + data lenth which results in a wrong lenght for the BlockLength

**Comment by fbarresi** [comment]
Thank you for that. The problem was solved merging your pull request.
